#!/bin/bash

HOST=openchirp.andrew.cmu.edu

export LOG_LEVEL=5
export FRAMEWORK_SERVER=http://$HOST:7000
export MQTT_SERVER=tls://$HOST:1883

# Set the following two lines to your OpenChirp device id and device token
export DEVICE_ID=ffffffffffffffffffffffff
export DEVICE_TOKEN=ffffffffffffffffffffffffffffff

#export INTERVAL=60s
#export DISK_PATH="/"


# Build the binary first
go build -o sysmonitor-device main.go
exec ./sysmonitor-device
